### ISSUE TITLE
Curie icon ideas

### ISSUE THREAD

**Issue by piotrwach** [macvmio/curie#128]
It would be good to have a more distinctive icon for Currie. At first I have not noticed it is even running, because it looks like this for me:

<img width="47" alt="Screenshot 2024-11-11 at 09 00 07" src="https://github.com/user-attachments/assets/9484b59d-8159-4b19-845c-2d93f99c2691">

**Comment by marciniwanicki** [comment]
Thank you @piotrwach, good point. Interesting, I wasn't aware of this behaviour. I always saw terminal-like icon, but I guess since the app does not have its own icon, `NSApplication` inherits the icon from the parent process. I will try to prepare and set an icon in the next few weeks.

**Comment by marciniwanicki** [comment]
Resolving. @piotrwach, hope you will like the new icon.

**Comment by piotrwach** [comment]
The new icon looks great! Thanks!
<img width="70" alt="Screenshot 2024-11-20 at 21 23 09" src="https://github.com/user-attachments/assets/c04223c8-b6ff-4f7a-9a26-5f8d791b1e40">
